FROM debian:bookworm-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 python3-pip cifs-utils procps iproute2 iputils-ping && \
    rm -rf /var/lib/apt/lists/*
RUN pip3 install --break-system-packages --no-cache-dir impacket
COPY mount_shares.py /opt/mount_shares.py
WORKDIR /opt
