FROM debian:bookworm-slim
RUN apt-get update && \
    apt-get install -y --no-install-recommends samba samba-common-bin procps && \
    rm -rf /var/lib/apt/lists/*
COPY smb.conf /etc/samba/smb.conf
COPY setup_shares.sh /setup_shares.sh
RUN chmod +x /setup_shares.sh
EXPOSE 445
ENTRYPOINT ["/setup_shares.sh"]
